#Find Max count Sub String with K length -BioInformatics
#Using dataset_2_13.txt
def CountFreq(str, k):
    maxx = -1000009;
    freq = {}
    ListString = []
    n = len(str)
    for i in range (n-k+1):
        str1 = str[i:i+k]
        if str1 in freq:
            freq[str1] += 1;
        else:
            freq[str1] = 1;
        maxx = max(maxx, freq[str1]);
    for i in freq:
        if freq[i] == maxx:
            ListString.append(i);
    return ListString, maxx, freq
'''str = "GTGGAACGGTGGAACGGGAGACCGCGGCACCGTCTCGGTTGCCGTGGAACGGTGGAACGGGCACCGTCCTTCCCGCTAGTGGAACGTCGGTTGCCTCGGTTGCCTCGGTTGCCCTTCCCGCTAGGCACCGTCCTTCCCGCTACTTCCCGCTAGTGGAACGCTTCCCGCTAGTGGAACGGGAGACCGCGGAGACCGCTCGGTTGCCGGAGACCGCGGCACCGTCTCGGTTGCCGGCACCGTCCTTCCCGCTAGTGGAACGGTGGAACGTCGGTTGCCGTGGAACGGTGGAACGGTGGAACGGGAGACCGCCTTCCCGCTAGGAGACCGCTCGGTTGCCGTGGAACGCTTCCCGCTAGGAGACCGCGGCACCGTCTCGGTTGCCGTGGAACGCTTCCCGCTATCGGTTGCCGGCACCGTCTCGGTTGCCGGCACCGTCCTTCCCGCTATCGGTTGCCGTGGAACGGGAGACCGCTCGGTTGCCGGAGACCGCGTGGAACGGTGGAACGGGAGACCGCGTGGAACGGTGGAACGGGAGACCGCTCGGTTGCCGTGGAACGGGCACCGTCGTGGAACGGGAGACCGCGGCACCGTCTCGGTTGCCGGCACCGTCCTTCCCGCTATCGGTTGCCGTGGAACGGTGGAACGGGCACCGTCTCGGTTGCCGGCACCGTCGGCACCGTCTCGGTTGCCCTTCCCGCTATCGGTTGCCGTGGAACGGGCACCGTCGGAGACCGCGGCACCGTCGTGGAACGTCGGTTGCCTCGGTTGCCTCGGTTGCCGGAGACCGCGGCACCGTCTCGGTTGCCTCGGTTGCCTCGGTTGCCGGAGACCGCGTGGAACGGTGGAACGGGAGACCGCGTGGAACGTCGGTTGCCCTTCCCGCTAGGAGACCGCCTTCCCGCTAGGAGACCGCGGCACCGTCGGAGACCGCGTGGAACGGTGGAACGGTGGAACGTCGGTTGCCCTTCCCGCTAGGCACCGTC"
k = 13;
#print(CountFreq(str, k));'''
lines = []
with open('dataset_2_13.txt') as f:
    lines = f.readlines()
k = int(lines[1])
print(CountFreq(lines[0], k))
